services:
    Octopouce\BlogBundle\:
        resource: '../../*'
        exclude: '../../{DependencyInjection,Entity,Resources}'
        autowire: true
        autoconfigure: true
        public: false

    Octopouce\BlogBundle\EventListener\PostUploadListener:
        tags:
            - { name: doctrine.event_listener, event: postLoad }